apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: catalogapi-hpa
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 2  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogapi-deployment
  targetCPUUtilizationPercentage: 50 # target CPU utilization
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: aspnetrunbasics-hpa
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 3  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aspnetrunbasics-deployment
  targetCPUUtilizationPercentage: 50 # target CPU utilization