apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetrunbasics-deployment
  labels:
    app: aspnetrunbasics
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aspnetrunbasics
  template:
    metadata:
      labels:
        app: aspnetrunbasics
    spec:
      containers:
        - name: aspnetrunbasics
          image: aspnetrunbasicsacr.azureacr.io/aspnetrunbasicsclient:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: CatalogAPIUrl
              valueFrom:
                  configMapKeyRef:
                    name: catalogapi-configmap
                    key: catalogapi_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
      imagePullPolicy:
        - name: acr-secret 
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetrunbasics-service
spec:
  type: LoadBalancer
  selector:
    app: aspnetrunbasics
  ports:
    - protocol: TCP
      port: 80