version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
 
  mongoclient:
    container_name: mongoclient
    ports:
      - "3000:3000"

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  orderdb:
    container_name: orderdb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  identityserverdb:
    container_name: identityserverdb
    environment:
      MYSQL_ROOT_PASSWORD: "Abcd1234"
    restart: always
    ports:
      - "3306:3306"
    volumes:
     - mysql_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Abcd1234"
      PMA_HOST: "identityserverdb"
      PMA_PORT: "3306"
    ports:
     - "8090:80"

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data 

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672" 

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - basketdb
      - rabbitmq 
    ports:
      - "8001:80"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - discountdb
    ports:
      - "8002:80"

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - discountdb
    ports:
      - "8003:80"

  order.api:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678;"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - orderdb
      - rabbitmq 
    ports:
      - "8004:80"

  ocelotapigateway:
    container_name: ocelot.gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - catalog.api
      - basket.api
      - discount.api
      - order.api 
    ports:
      - "8010:80"

  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:CatalogUrl=http://catalog.api"
      - "ApiSettings:BasketUrl=http://basket.api"
      - "ApiSettings:OrderUrl=http://order.api"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - catalog.api
      - basket.api
      - order.api
    ports:
      - "8005:80"

  aspnetrunbasics:
    container_name: aspnetrunbasics
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:GatewayAddress=http://ocelotapigateway"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - ocelotapigateway
      - discount.api
      - catalog.api
      - basket.api
      - order.api
    ports:
      - "8006:80"

  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:IdentityServerConnectionString=Server=identityserverdb;Port=3306;Database=IdentityServerDb;User Id=root;Password=Abcd1234;"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - identityserverdb
    ports:
      - "8007:80"

  elasticsearch:
    container_name: elasticsearch
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    ports:
        - "9200:9200"
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
        - elasticsearch
    ports:
        - "5601:5601"

  webstatus:
    container_name: webstatus
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - HealthChecksUI__HealthChecks__0__Name=Catalog Health Check
        - HealthChecksUI__HealthChecks__0__Uri=http://catalog.api/hc
        - HealthChecksUI__HealthChecks__1__Name=Basket Health Check
        - HealthChecksUI__HealthChecks__1__Uri=http://basket.api/hc
        - HealthChecksUI__HealthChecks__2__Name=Discount Health Check
        - HealthChecksUI__HealthChecks__2__Uri=http://discount.api/hc
        - HealthChecksUI__HealthChecks__3__Name=Order Health Check
        - HealthChecksUI__HealthChecks__3__Uri=http://order.api/hc
        - HealthChecksUI__HealthChecks__4__Name=Shopping Aggregator Health Check
        - HealthChecksUI__HealthChecks__4__Uri=http://shopping.aggregator/hc
        - HealthChecksUI__HealthChecks__5__Name=AspnetRunBasics WebMVC Health Check
        - HealthChecksUI__HealthChecks__5__Uri=http://aspnetrunbasics/hc    
    ports:
      - "8008:80"